version: "3.9"
services:
  build:
    # Run this compose by ensuring user and group id were set properly
    # Using
    #   USER_ID=$(id -u) 
    #   GROUP_ID=$(id -g)
    # Before you run this
    # This ensures that the build runs as our current user
    # And not as root which is default
    user: "${USER_ID}:${GROUP_ID}"
    # Use the following to run as root
    # user: root
    build:
      # Directory where to find the Docker file
      context: .
      dockerfile: Dockerfile
      # The Multi Stage Build Stage to use
      ## Using Ubuntu
      # target: ubuntu-builder
      ## Using CentOS 6
      target: centos-6-builder
    # The Folders to share
    # entrypoint: ["bash","-c","ls -lArth /;ls -lArth /code"]
    entrypoint: ["/buildtools/build.sh"]
    volumes:
      # RO indicates that we are mounting as read only
      # Which in Docker means writing here would lead to an error
      - ./code:/code:ro
      # Just because they are at the same source path
      # Does not mean they both need to be ro
      - ./code:/buildtools:ro
      # If not ro, use z which tells Docker that this
      # mount is writable and it belongs to the host
      # And is potentially being used for other purposes
      # Not doing this can lead to errors
      - ./output:/Output:z
  
  # Assuming this is not an Ubuntu system
  run-ubuntu:
    user: "${USER_ID}:${GROUP_ID}"
    image: ubuntu
    entrypoint: ["/App/Ubuntu.exe"]
    volumes:
      - ./output:/App:ro

    # Assuming this is not a CENTOS Family system
  run-centos-6:
    user: "${USER_ID}:${GROUP_ID}"
    build:
      # Directory where to find the Docker file
      context: .
      dockerfile: Dockerfile
      # The Multi Stage Build Stage to use
      ## Using Ubuntu
      target: centos-6-without-eol-issues
    entrypoint: ["/App/CentOS-6.exe"]
    volumes:
      - ./output:/App:ro